# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e35b7756801d076c18ad20390a2299da206cf1f69d83f516b279964205de5e3650fd87dfd4f8ff942b15a1a65957fb69d04d65b3295d6780620949fff4f1d60

test:
  secret_key_base: 8534e982982fc3caf1ee9480218aa0995908c004ba6fa346ee71c2410184b26b917b14a0a396491538d3b47d905d5e5a9146fb05c4123ca00faa5fb9ad0d1639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
